# Generated by Django 5.2.3 on 2025-07-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='box_office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
