# Generated by Django 5.2.3 on 2025-07-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_actors_movie_awards_movie_box_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
